### PR TITLE
fix(report): waiting promise resolve in onExist method fix #418

### LINKED ISSUE #418: Regression v2.0.1 -> v2.0.2: Exit code not set when thresholds aren't met
As already mentioned in [my comment](https://github.com/karma-runner/karma-coverage/pull/403/files#r436609574), there is a regression caused by #403 which prevents the exit code from being set in time, which causes the process not to fail in case the coverage threshold is not met.

I've created a small example to show-case the current behavior and also did some PoC on how it might be solved:
https://github.com/matz3/issue-karma-coverage-threshold-exit-code

Here are the changes to karma and karma-coverage
- https://github.com/karma-runner/karma/pull/3541
- https://github.com/karma-runner/karma-coverage/pull/420

With v2.0.1 everything seems to work fine.

### PR DESCRIPTION
**Pull request by anthony-redFox**
onComplete are async method which should bw complete in onExit method

### CODE REVIEW

File: lib/reporter.js [hunk 1]
```diff
@@ -218,58 +218,77 @@ var CoverageReporter = function (rootConfig, helper, logger, emitter) {
...
+
+    const promiseCollection = reporters.map(reporterConfig =>
+      Promise.all(browsers.map(async (browser) => {
+        const res = await this.executeReport(reporterConfig, browser)
+        if (res && res.exitCode === 1) {
+          results = res
+        }
+      })))
+    promiseComplete = Promise.all(promiseCollection).then(() => results)
+    return promiseComplete
```
Comment (matz3) [inline lib/reporter.js:283]: `onRunComplete` is sync without any return value, right?
Karma just expects you to modify the provided `results` object (2nd parameter). But this needs to be done synchronously, which doesn't work here as the istanbul API is async.

So to avoid confusion, I would suggest to remove the `return` statement here.

File: lib/reporter.js [hunk 2]
```diff
@@ -218,58 +218,77 @@ var CoverageReporter = function (rootConfig, helper, logger, emitter) {
...
+  }
+
+  this.onExit = async function (done) {
+    const results = await promiseComplete
+    if (results && results.exitCode === 1) {
+      done(results.exitCode)
+      return
+    }
     if (typeof config._onExit === 'function') {
       config._onExit(done)
```
Comment (matz3) [inline lib/reporter.js:293]: Not sure where this function gets defined or where it's used, but it won't be called in case exitCode is 1.
See #420 for my approach, which still calls it.

File: lib/reporter.js [hunk 3]
```diff
@@ -218,58 +218,77 @@ var CoverageReporter = function (rootConfig, helper, logger, emitter) {
...
+        if (res && res.exitCode === 1) {
+          results = res
+        }
+      })))
+    promiseComplete = Promise.all(promiseCollection).then(() => results)
+    return promiseComplete
+  }
+
+  this.onExit = async function (done) {
+    const results = await promiseComplete
```
Comment (matz3) [inline lib/reporter.js:287]: There is no error handling by karma in case `promiseComplete` rejects. Karma doesn't expect the `onExit` handlers to return a promise. I would suggest using plain old `then` to handle success/error. See my code in #420

Comment (anthony-redFox) [reply lib/reporter.js:287]: await works with success only, if will be error the code onExit will be failed

File: lib/reporter.js (hunk 2 above)
Comment (anthony-redFox) [reply lib/reporter.js:293]: Are you sure that will be useful to call callback onExit? custom code can call with 1 or 0 too but you are ignore it.

File: lib/reporter.js (hunk 1 above)
Comment (anthony-redFox) [reply lib/reporter.js:283]: It is need for Unit test to wait async operations

File: lib/reporter.js (hunk 2 above)
Comment (anthony-redFox) [reply lib/reporter.js:293]: Build will be failed. Is matter to execute onExit method?

File: lib/reporter.js (hunk 3 above)
Comment (matz3) [reply lib/reporter.js:287]: `onExit` is called sync by the karma-runner and expects the callback to be invoked. It doesn't expect a promise to be returned. That's why I suspect that a rejection would result into an unhandled Promise rejection.

File: lib/reporter.js (hunk 2 above)
Comment (matz3) [reply lib/reporter.js:293]: I don't know where `_onExit` is defined or used, but with this change it's not called anymore in case the `exitCode` is `1`. That's what I wanted to note here.
